INSERT INTO SUPER_HEROES(ID, NOMBRE, FUERZA, RESISTENCIA) VALUES(90001, 'SuperMan', 4,6);
INSERT INTO SUPER_HEROES(ID, NOMBRE, FUERZA, RESISTENCIA) VALUES(90002, 'Spiderman', 1,2);
INSERT INTO SUPER_HEROES(ID, NOMBRE, FUERZA, RESISTENCIA) VALUES(90003, 'Lucas', 8,5);
INSERT INTO SUPER_HEROES(ID, NOMBRE, FUERZA, RESISTENCIA) VALUES(90004, 'Manolo', 1,3);
 

